services:
  frontend:
    build: 
      context: mern/frontend
    image: frontend-mern
    container_name: frontend
    networks:
      - mern
    ports:
      - "5173:5173"

  backend:
    build: 
      context: mern/backend
    image: backend-mern
    container_name: backend
    ports:
      - "5050:5050"
    networks:
      - mern
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: database
    volumes:
       - mongodata:/data/db
    networks:
      - mern
    ports:
      - "27017:27017"

networks:
  mern:
    driver: bridge

volumes:
  mongodata:
    driver: local
